# Vektorisierung [Python]

In Python lässt sich eine Matrix mit [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) vektorisieren. Normalerweise geschieht dies durch Verkettung der Zeilen, weil in einem Array die Daten geschachtelt werden und deren Struktur so erhalten bleibt.

$$\begin{align*} \forall i\in\{0,\ldots,m-1\},\forall j\in\{0,\ldots,n-1\}&\colon\\\\ (j,i) \mapsto&~ jm+i \end{align*}$$

![Verkettung Python](../.Dateien/Bilder/Verkettung_Python.svg)

In [1]:
import numpy as np

m = 3
n = 2

A = np.ones((n,m))
a = np.reshape(A,(n*m))

Hier wurde eine `2×3`-Matrix in einen Vektor überführt.

In [2]:
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
a

array([1., 1., 1., 1., 1., 1.])

Diese Operation lässt sich auch umkehren.

In [4]:
B = np.reshape(a,(n,m))
B

array([[1., 1., 1.],
       [1., 1., 1.]])